version: "1.0.1-{build}"
skip_tags: true
image: Ubuntu2004
clone_depth: 1
branches:
  only:
    - master
    - /rc\/([\d\w\-\.]+)/
environment:
  PY_VER: 3.11
init:
  - sh: source $HOME/venv$PY_VER/bin/activate
  - sh: python --version
build: false
install:
  - python -m pip install "pip>=21" "wheel>=0.37" || python -c "print('')"
  - python -m pip install --upgrade --prefer-binary tox
test_script:
  - python -m tox r --discover "$HOME/venv3.7/bin/python" "$HOME/venv3.8/bin/python" "$HOME/venv3.9/bin/python" "$HOME/venv3.10/bin/python" "$HOME/venv3.11/bin/python" "$HOME/venv3.12/bin/python"
on_finish:
  - sh: find . -type f -name 'tests-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
